CREATE TABLE sources (
	id		INTEGER PRIMARY KEY AUTOINCREMENT,
	tName	TEXT	NOT NULL,
	tPath	TEXT	NOT NULL,
	tType	TEXT	CHECK(tType IN ('GITHUB', 'GITLAB', 'MANGADEX')),
	tDate	TEXT	NOT NULL DEFAULT '1970-01-01 00:00:00.000'
);
